[package]
name = "avro-schema"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = { version = "1.0", default-features = false, features = ["std"] }
serde = { version = "1.0", default-features = false }
